#!/usr/bin/env bash
# Security + concurrency regression tests for the delegated customer-admin setup backend
# (migration 20260827120000_delegated_setup_tasks.sql). Runs against the LOCAL Supabase
# stack via the db container — no network, no prod. Exits non-zero on any failure.
#
# Run: bash scripts/delegated-setup-security.test.sh
# Requires: local Supabase stack up (docker container supabase_db_<project>).
set -uo pipefail

CONTAINER="${SUPABASE_DB_CONTAINER:-supabase_db_serviceos-dh}"
FAILED=0
q() { docker exec "$CONTAINER" psql -U postgres -d postgres -tAc "$1" 2>&1; }
h() { printf '%s' "$1" | shasum -a 256 | cut -d' ' -f1; }
check() { # name expected actual
  if [ "$2" = "$3" ]; then echo "  PASS: $1"; else echo "  FAIL: $1 (expected [$2] got [$3])"; FAILED=1; fi
}

TENANT=$(q "select id from public.tenants limit 1;")
[ -z "$TENANT" ] && { echo "no tenant found — is the local stack seeded?"; exit 2; }
q "delete from public.delegated_setup_tasks where recipient_email like '%@sectest.local';" >/dev/null

echo "delegated-setup security tests (tenant=$TENANT)"

# raw token is generated by the caller; only the hash reaches the DB.
RAW="sectest-raw-$$-primary"; H=$(h "$RAW"); HX=$(h "sectest-wrong-$$")
TID=$(q "select public.delegated_task_issue('$TENANT','provide_telephony_inventory','provide', array['endpoint_type','value'], 'A.Admin@Sectest.LOCAL ','Admin','sipcentric',null,'$H','${RAW: -4}',3600,true,1,null);")

check "raw token never stored (no row matches raw)" "0" "$(q "select count(*) from public.delegated_setup_tasks where token_hash='$RAW';")"
check "hash IS stored" "t" "$(q "select token_hash='$H' from public.delegated_setup_tasks where id='$TID';")"
check "recipient email normalised to lowercase/trim" "a.admin@sectest.local" "$(q "select recipient_email from public.delegated_setup_tasks where id='$TID';")"
check "verify valid token" "valid" "$(q "select resolution from public.delegated_task_verify('$H');")"
check "verify wrong token = not_found (no existence leak)" "not_found" "$(q "select resolution from public.delegated_task_verify('$HX');")"
check "mark opened" "t" "$(q "select public.delegated_task_mark_opened('$H');")"
# Capture erroring psql output FIRST (piping an erroring command into grep trips pipefail).
SUBERR=$(q "select public.delegated_task_submit('$H','{\"password\":\"x\"}'::jsonb);")
check "submit rejects out-of-scope field" "ERR" "$(echo "$SUBERR" | grep -qi 'not permitted' && echo ERR || echo OK)"
check "submit accepts allowed fields" "t" "$(q "select public.delegated_task_submit('$H','{\"endpoint_type\":\"ddi\",\"value\":\"+441\"}'::jsonb);")"
check "complete once succeeds" "t" "$(q "select public.delegated_task_complete('$H');")"
check "replay complete blocked" "f" "$(q "select public.delegated_task_complete('$H');")"
check "no raw token in any event detail" "f" "$(q "select bool_or(detail::text ilike '%$RAW%') from public.delegated_setup_events where task_id='$TID';")"

# Concurrency: two parallel completes on a fresh single-use task -> exactly one succeeds.
RAWR="sectest-race-$$"; HR=$(h "$RAWR")
q "select public.delegated_task_issue('$TENANT','confirm_company_domains','c', array['domain'],'race@sectest.local',null,null,null,'$HR','race',3600,true,1,null);" >/dev/null
docker exec "$CONTAINER" psql -U postgres -d postgres -tAc "select public.delegated_task_complete('$HR');" >/tmp/dst_a 2>&1 &
docker exec "$CONTAINER" psql -U postgres -d postgres -tAc "select public.delegated_task_complete('$HR');" >/tmp/dst_b 2>&1 &
wait
check "race: exactly one complete wins" "1" "$(cat /tmp/dst_a /tmp/dst_b | grep -c '^t$')"
check "race: use_count is exactly 1" "1" "$(q "select use_count from public.delegated_setup_tasks where token_hash='$HR';")"

# max_uses>1 (not single-use)
RAWM="sectest-multi-$$"; HM=$(h "$RAWM")
q "select public.delegated_task_issue('$TENANT','confirm_company_domains','c', array['domain'],'multi@sectest.local',null,null,null,'$HM','mult',3600,false,2,null);" >/dev/null
check "max_uses enforced (t,t,f)" "t,t,f" "$(printf '%s,%s,%s' "$(q "select public.delegated_task_complete('$HM');")" "$(q "select public.delegated_task_complete('$HM');")" "$(q "select public.delegated_task_complete('$HM');")")"

# expiry
RAWE="sectest-exp-$$"; HE=$(h "$RAWE")
TIDE=$(q "select public.delegated_task_issue('$TENANT','confirm_company_domains','c', array['domain'],'exp@sectest.local',null,null,null,'$HE','expr',3600,true,1,null);")
q "update public.delegated_setup_tasks set expires_at=now()-interval '1 hour' where id='$TIDE';" >/dev/null
check "expired token verify" "expired" "$(q "select resolution from public.delegated_task_verify('$HE');")"
check "complete after expiry blocked" "f" "$(q "select public.delegated_task_complete('$HE');")"

# revoke (operator)
RAWV="sectest-rev-$$"; HV=$(h "$RAWV")
TIDV=$(q "select public.delegated_task_issue('$TENANT','confirm_company_domains','c', array['domain'],'rev@sectest.local',null,null,null,'$HV','revk',3600,true,1,'$TENANT');")
q "select public.delegated_task_revoke('$TIDV','$TENANT');" >/dev/null
check "revoked token verify" "revoked" "$(q "select resolution from public.delegated_task_verify('$HV');")"
check "complete after revoke blocked" "f" "$(q "select public.delegated_task_complete('$HV');")"

# tenant isolation / deny-all RLS (capture first — erroring psql + pipefail)
RLS_SEL=$(docker exec "$CONTAINER" psql -U postgres -d postgres -tAc "set role authenticated; select count(*) from public.delegated_setup_tasks;" 2>&1)
check "authenticated cannot SELECT tasks (deny-all)" "DENIED" "$(echo "$RLS_SEL" | grep -qi 'permission denied' && echo DENIED || echo OPEN)"
RLS_EXE=$(docker exec "$CONTAINER" psql -U postgres -d postgres -tAc "set role authenticated; select public.delegated_task_verify('x');" 2>&1)
check "authenticated cannot EXECUTE token RPCs" "DENIED" "$(echo "$RLS_EXE" | grep -qi 'permission denied' && echo DENIED || echo OPEN)"

q "delete from public.delegated_setup_tasks where recipient_email like '%@sectest.local';" >/dev/null
echo ""
if [ "$FAILED" = "0" ]; then echo "ALL DELEGATED-SETUP SECURITY TESTS PASSED"; exit 0; else echo "SECURITY TESTS FAILED"; exit 1; fi
