/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthShadowRouteImport } from './routes/health-shadow'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoCustomerHealthRouteImport } from './routes/demo.customer-health'
import { Route as DemoCommandCentreRouteImport } from './routes/demo.command-centre'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthShadowRoute = HealthShadowRouteImport.update({
  id: '/health-shadow',
  path: '/health-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCustomerHealthRoute = DemoCustomerHealthRouteImport.update({
  id: '/demo/customer-health',
  path: '/demo/customer-health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCommandCentreRoute = DemoCommandCentreRouteImport.update({
  id: '/demo/command-centre',
  path: '/demo/command-centre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/health-shadow': typeof HealthShadowRoute
  '/login': typeof LoginRoute
  '/demo/command-centre': typeof DemoCommandCentreRoute
  '/demo/customer-health': typeof DemoCustomerHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/health-shadow': typeof HealthShadowRoute
  '/login': typeof LoginRoute
  '/demo/command-centre': typeof DemoCommandCentreRoute
  '/demo/customer-health': typeof DemoCustomerHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/health-shadow': typeof HealthShadowRoute
  '/login': typeof LoginRoute
  '/demo/command-centre': typeof DemoCommandCentreRoute
  '/demo/customer-health': typeof DemoCustomerHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/health-shadow'
    | '/login'
    | '/demo/command-centre'
    | '/demo/customer-health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/health-shadow'
    | '/login'
    | '/demo/command-centre'
    | '/demo/customer-health'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/health-shadow'
    | '/login'
    | '/demo/command-centre'
    | '/demo/customer-health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  HealthShadowRoute: typeof HealthShadowRoute
  LoginRoute: typeof LoginRoute
  DemoCommandCentreRoute: typeof DemoCommandCentreRoute
  DemoCustomerHealthRoute: typeof DemoCustomerHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-shadow': {
      id: '/health-shadow'
      path: '/health-shadow'
      fullPath: '/health-shadow'
      preLoaderRoute: typeof HealthShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/customer-health': {
      id: '/demo/customer-health'
      path: '/demo/customer-health'
      fullPath: '/demo/customer-health'
      preLoaderRoute: typeof DemoCustomerHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/command-centre': {
      id: '/demo/command-centre'
      path: '/demo/command-centre'
      fullPath: '/demo/command-centre'
      preLoaderRoute: typeof DemoCommandCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  HealthShadowRoute: HealthShadowRoute,
  LoginRoute: LoginRoute,
  DemoCommandCentreRoute: DemoCommandCentreRoute,
  DemoCustomerHealthRoute: DemoCustomerHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
